import 'package:cmzoofv2/service/data/cardata.dart';
import 'package:cmzoofv2/ui/detail/detailcar.dart';
import 'package:flutter/material.dart';

class CarPage extends StatefulWidget {
  @override
  _CarPageState createState() => _CarPageState();
}

class _CarPageState extends State<CarPage> {
  List<CarData> carout = [
    new CarData("8:30 - 8:40"),
    new CarData("8:40 - 8:50"),
    new CarData("8:50 - 9:00"),
    new CarData("9:00 - 9:10"),
    new CarData("9:10 - 9:20"),
    new CarData("9:20 - 9:30"),
    new CarData("9:30 - 9:40"),
    new CarData("9:40 - 9:50"),
    new CarData("9:50 - 10:00"),
    new CarData("10:00 - 10:10"),
    new CarData("10:10 - 10:20"),
    new CarData("10:20 - 10:30"),
    new CarData("10:30 - 10:40"),
    new CarData("10:40 - 10:50"),
    new CarData("10:50 - 11:00"),
    new CarData("11:00 - 11:10"),
    new CarData("11:10 - 11:20"),
    new CarData("11:20 - 11:30"),
    new CarData("11:30 - 11:40"),
    new CarData("11:40 - 11:50"),
    new CarData("11:50 - 12:00"),
    new CarData("12:00 - 12:10"),
    new CarData("12:10 - 12:20"),
    new CarData("12:20 - 12:30"),
    new CarData("12:30 - 12:40"),
    new CarData("12:40 - 12:50"),
    new CarData("12:50 - 13:00"),
    new CarData("13:00 - 13:10"),
    new CarData("13:10 - 13:20"),
    new CarData("13:20 - 13:30"),
    new CarData("13:30 - 13:40"),
    new CarData("13:40 - 13:50"),
    new CarData("13:50 - 14:00"),
    new CarData("14:00 - 14:10"),
    new CarData("14:10 - 14:20"),
    new CarData("14:20 - 14:30"),
    new CarData("14:30 - 14:40"),
    new CarData("14:40 - 14:50"),
    new CarData("14:50 - 15:00"),
    new CarData("15:00 - 15:10"),
    new CarData("15:10 - 15:20"),
    new CarData("15:20 - 15:30"),
    new CarData("15:30 - 15:40"),
    new CarData("15:40 - 15:50"),
    new CarData("15:50 - 16:00"),
    new CarData("16:00 - 16:10"),
    new CarData("16:10 - 16:20"),
    new CarData("16:20 - 16:30"),
  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.lightGreen[100],
      appBar: AppBar(
        centerTitle: true,
        automaticallyImplyLeading: false,
        backgroundColor: Colors.lightGreen[900],
        title: Text(
          'รถบริการชมรอบสวนสัตว์',
          textAlign: TextAlign.center,
          style: TextStyle(
            fontSize: 20.0,
            fontWeight: FontWeight.bold,
            fontFamily: 'mitr',
          ),
        ),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.symmetric(vertical: 16.0, horizontal: 18.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                "เวลาให้บริการของรถบริการชมสวนสัตว์",
                style: TextStyle(
                  color: Colors.green[900],
                  fontSize: 22.0,
                  fontWeight: FontWeight.w600,
                  fontFamily: 'mitr',
                ),
              ),
              SizedBox(
                height: 8.0,
              ),
              detailCar(carout[0]),
              detailCar(carout[1]),
              detailCar(carout[2]),
              detailCar(carout[3]),
              detailCar(carout[4]),
              detailCar(carout[5]),
              detailCar(carout[6]),
              detailCar(carout[7]),
              detailCar(carout[8]),
              detailCar(carout[9]),
              detailCar(carout[10]),
              detailCar(carout[11]),
              detailCar(carout[12]),
              detailCar(carout[13]),
              detailCar(carout[14]),
              detailCar(carout[15]),
              detailCar(carout[16]),
              detailCar(carout[17]),
              detailCar(carout[18]),
              detailCar(carout[19]),
              detailCar(carout[20]),
              detailCar(carout[21]),
              detailCar(carout[22]),
              detailCar(carout[23]),
              detailCar(carout[24]),
              detailCar(carout[25]),
              detailCar(carout[26]),
              detailCar(carout[27]),
              detailCar(carout[28]),
              detailCar(carout[29]),
              detailCar(carout[30]),
              detailCar(carout[31]),
              detailCar(carout[32]),
              detailCar(carout[33]),
              detailCar(carout[34]),
              detailCar(carout[35]),
              detailCar(carout[36]),
              detailCar(carout[37]),
              detailCar(carout[38]),
              detailCar(carout[39]),
              detailCar(carout[40]),
              detailCar(carout[41]),
              detailCar(carout[42]),
              detailCar(carout[43]),
              detailCar(carout[44]),
              detailCar(carout[45]),
              detailCar(carout[46]),
              detailCar(carout[47]),
            ],
          ),
        ),
      ),
    );
  }
}
